wandb_version: 1

batch_size:
  desc: null
  value: 256
beta1:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.00034712676394152496
training_itr:
  desc: null
  value: 157543
weight_decay:
  desc: null
  value: 0.0014214333350734487
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695970671.511914
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
