wandb_version: 1

batch_size:
  desc: null
  value: 128
beta1:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.0008462107318887306
training_itr:
  desc: null
  value: 104633
weight_decay:
  desc: null
  value: 0.008189600893066855
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695970418.19399
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
