wandb_version: 1

batch_size:
  desc: null
  value: 256
beta1:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.0009213059301201156
training_itr:
  desc: null
  value: 160421
weight_decay:
  desc: null
  value: 0.00028043450323104736
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695975976.235062
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
