wandb_version: 1

batch_size:
  desc: null
  value: 16
beta1:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.0008303035615611965
training_itr:
  desc: null
  value: 69662
weight_decay:
  desc: null
  value: 0.008445518541994986
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695967504.501367
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
