wandb_version: 1

learning_rate:
  desc: null
  value: 0.0003
batch size:
  desc: null
  value: 32
weight decay:
  desc: null
  value: 0
beta 1:
  desc: null
  value: 0.9
training itr:
  desc: null
  value: 100000
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695942075.742235
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
