wandb_version: 1

batch_size:
  desc: null
  value: 16
beta1:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.0007109663856808858
training_itr:
  desc: null
  value: 81005
weight_decay:
  desc: null
  value: 0.008049671214635417
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695965293.872172
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 37
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
